### Get a word

GET {{http_url}}/word/{{word}}

### Get random word

POST {{http_url}}/word/random

### Push a word

POST {{http_url}}/word
Content-Type: application/json

{
  "word": "{{word}}"
}

### Delete a word

DELETE {{http_url}}/word
Content-Type: application/json

{
  "word": "{{word}}"
}

### Test chain of services HTTP

POST {{http_url}}/word/chain
Content-Type: application/json

{
  "count": 5,
  "input": [
    "aaa",
    "bbb"
  ]
}

### Test chain of services gRPC

GRPC {{grpc_url}}/word.WordService/Chain

{
  "count": 5,
  "input": [
    "aaa",
    "bbb"
  ]
}
