apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-service.fullname" . }}
  labels:
    {{- include "example-service.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
    {{- if .connectedServices }}
  EXAMPLE_SERVICE_GRPC_CONNECTED_SERVICES: {{ .connectedServices | join "," | quote }}
    {{- end }}
  {{- end }}

  OTEL_SERVICE_NAME: {{ include "example-service.fullname" . }}
  OTEL_RESOURCE_ATTRIBUTES: env=kubernetes

  {{- with .Values.logs }}
  RUST_LOG: {{ .level | quote }}
    {{- if .backtrace }}
  RUST_BACKTRACE: "1"
    {{- else }}
  RUST_BACKTRACE: "0"
    {{- end }}
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: {{ .endpoint | quote }}
  OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: "http/protobuf"
  {{- end }}

  {{- with .Values.metrics }}
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: {{ .endpoint | quote }}
  MONITORING_METRICS_PUSH_INTERVAL: {{ .pushInterval | quote }}
  OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: "http/protobuf"
  {{- end }}

  {{- with .Values.traces }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .endpoint | quote }}
  OTEL_TRACES_SAMPLER_ARG: {{ .sampleRatio | quote }}
  OTEL_TRACES_SAMPLER: traceidratio
  {{- end }}
