apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-service.fullname" . }}
  labels:
    {{- include "example-service.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
    RUST_LOG: {{ .logLevel | quote }}
    {{- if .backtrace }}
    RUST_BACKTRACE: "1"
    {{- else }}
    RUST_BACKTRACE: "0"
    {{- end }}
    CONNECTED_SERVICES: {{ .connectedServices | join "," | quote }}
  {{- end }}
