services:
  service-1:
    build:
      context: .
      target: final
    image: ${DOCKER_REGISTRY:-harbor.internal.roxxas96.net/example-app}/example-service:${VERSION:-latest}
    ports:
      - 3001:3001
      - 50051:50051
      - 9001:9001
    environment:
      - CONNECTED_SERVICES=grpc://service-2:50051,grpc://service-3:50051,grpc://service-4:50051,grpc://service-5:50051
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-1}
    healthcheck:
      test: curl --fail http://localhost:3001/health
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  service-2:
    build:
      context: .
      target: final
    image: ${DOCKER_REGISTRY:-harbor.internal.roxxas96.net/example-app}/example-service:${VERSION:-latest}
    ports:
      - 3002:3001
      - 50052:50051
      - 9002:9001
    environment:
      - CONNECTED_SERVICES=grpc://service-1:50051,grpc://service-3:50051,grpc://service-4:50051,grpc://service-5:50051
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-1}
    healthcheck:
      test: curl --fail http://localhost:3001/health
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  service-3:
    build:
      context: .
      target: final
    image: ${DOCKER_REGISTRY:-harbor.internal.roxxas96.net/example-app}/example-service:${VERSION:-latest}
    ports:
      - 3003:3001
      - 50053:50051
      - 9003:9001
    environment:
      - CONNECTED_SERVICES=grpc://service-1:50051,grpc://service-2:50051,grpc://service-4:50051,grpc://service-5:50051
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-1}
    healthcheck:
      test: curl --fail http://localhost:3001/health
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  service-4:
    build:
      context: .
      target: final
    image: ${DOCKER_REGISTRY:-harbor.internal.roxxas96.net/example-app}/example-service:${VERSION:-latest}
    ports:
      - 3004:3001
      - 50054:50051
      - 9004:9001
    environment:
      - CONNECTED_SERVICES=grpc://service-1:50051,grpc://service-2:50051,grpc://service-3:50051,grpc://service-5:50051
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-1}
    healthcheck:
      test: curl --fail http://localhost:3001/health
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  service-5:
    build:
      context: .
      target: final
    image: ${DOCKER_REGISTRY:-harbor.internal.roxxas96.net/example-app}/example-service:${VERSION:-latest}
    ports:
      - 3005:3001
      - 50055:50051
      - 9005:9001
    environment:
      - CONNECTED_SERVICES=grpc://service-1:50051,grpc://service-2:50051,grpc://service-3:50051,grpc://service-4:50051
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-1}
    healthcheck:
      test: curl --fail http://localhost:3001/health
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  prometheus:
    image: bitnami/prometheus:3.5.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/opt/bitnami/prometheus/prometheus.yml
    command:
      - --web.enable-otlp-receiver
  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    ports:
      - 4317:4317
      - 16686:16686
  loki:
    image: bitnami/grafana-loki:3.5.2
    ports:
      - 3100:3100
    volumes:
      - ./loki.yaml:/bitnami/grafana-loki/conf/loki.yaml:ro

  grafana:
    image: bitnami/grafana:12.0.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
