apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v1.0.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.32.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.32.0/interceptors.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.58.0/release.yaml
  - tasks
  - pipelines
  - triggers
  - example-app-repo.sealedsecret.yaml
  - docker-repo.sealedsecret.yaml
  - ingress.yaml

patches:
  - path: namespace.patch.yaml
