apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger
spec:
  image: jaegertracing/jaeger:2.8.0
  env:
    - name: CASSANDRA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jaeger-cassandra
          key: cassandra-password
    - name: SPAN_STORAGE_TTL
      value: 240h
  ports:
    - name: jaeger
      port: 16686
  config:
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaeger_storage_exporter]
    extensions:
      jaeger_query:
        storage:
          traces: cassandra_storage
      jaeger_storage:
        backends:
          cassandra_storage:
            cassandra:
              schema:
                keyspace: jaeger_tracing
                create: true
              connection:
                auth:
                  basic:
                    username: cassandra
                    password: "${env:CASSANDRA_PASSWORD}"
                tls:
                  insecure: true
                servers: ["jaeger-cassandra:9042"]
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      jaeger_storage_exporter:
        trace_storage: cassandra_storage
