apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chart-testing
subjects:
  - kind: ServiceAccount
    name: chart-testing
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: chart-testing
  apiGroup: rbac.authorization.k8s.io
