apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  - https://api.hub.tekton.dev/v1/resource/tekton/task/git-clone/0.9/raw
  - pre-commits.yaml
  - example-app-bump-version.yaml
  - commit-changes.yaml
