apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - service-account.yaml
  - webhook.sealedsecret.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - trigger-template.yaml
  - on-push
