apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: example-app-execute-ci
spec:
  params:
    - name: git-revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...).
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: example-app-ci-run-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: example-app-ci
        serviceAccountName: chart-testing
        podTemplate:
          securityContext:
            fsGroup: 65532
          imagePullSecrets:
            - name: harbor-credentials
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: git-credentials
            secret:
              secretName: home-infra-ssh-key
          - name: docker-credentials
            secret:
              secretName: tekton-harbor-credentials
          - name: helm-credentials
            secret:
              secretName: tekton-helm-harbor-credentials
          - name: cosign-key
            secret:
              secretName: cosign-key
        params:
          - name: git-revision
            value: $(tt.params.git-revision)
