apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: tekton-pipelines
spec:
  encryptedData:
    secretToken: AgCHs4kE3ONXNsHlW0I4Am+s4wtLsiY0/p0zakZtjLbfH7dGL8OV2RBqaK5Xlp38/zdW0cg7pjMMo7x6xj8POpb4+jagNrez0w6t8wqzTptJOH4KXBTIwtUY9faN+lwbYt0rnFA70ms6cCvIWXnY024dZXnZ21rdXlHeW+qoQJ0HUYTxySTVsgboukXa2AHpeS8fmXbDGUzOa3y+014nMv6mOZZhkANbXrXy8hu4p/rs0uATcJoTukw2rT73I15bCKnRHTahmqeS29j9JwWeBvt/9Lt/O4DdEP8Azpit4Z06ul1rPrXYroKvVIrOSQk/pcMH7oT7hODfMJiVLtRdk8A3jPfhX9uc0P9xj+bprOw5T+TVIh+98zfYN1HD8rudLEzUUKSuqa3r6W5hQLA6sOpMz09uSC/lTjM+CNYhPxhN1k8DD0McPjXo9cgFuVrofP7DXk0Yh/ZkPmdV2It7d0yEbehG/Dr8zHjPSZFUlDQsJHDQtqcyzfPBJXRNAgcOte7eChe1T9CaMqFJIltIlfApTusMFre3WaLXJs2ZIQT9ITeg0GNm5Jm/mlnqu3RFXBVwFlGKgXZyvVAyDVXsVPROfhUqj8nWlxgidTZJDLJPfSBHdUEZQsNriVvHn36KdO9468dEEgFxhsZn8aJHRqlf8FW2rm56y5L6wmnEC3eLoIKrbU8FDXzHUHJ9WBTqjUkLoJVmKe2DaTIbja1f1g==
  template:
    metadata:
      name: github-secret
      namespace: tekton-pipelines
    type: Opaque
