---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: tekton-pipelines
spec:
  encryptedData:
    secretToken: AgAiUtuW7CmLGOlr0OOk70WrXKUaIU8spzlC8PDvTHDwdi8MZaogr8maOfg6MhUFmNUcWHmICNsupUUgYll9WQ6TOjGkeDYZp/G3munOHoOTqYfsho4WFs4cbB/KwEF0F/3HXG7Z7DLxIlgtxcgiy+Wk3Ut7OUFiF4J8vRIZ65wtOdl9gfwu6ynYKaDe1REYPEvXNUxwArSiRY98/rPJZZ851enlyu45ACNeDjjamXeT6kC/xnY8zCkfLakUdsBt4ScrheWGDIVraE/vdQD4WtO1WHa59+2O0r2bD8B12obMdWNe/asMutG3GNvi6Px1MrSJqChVr7o8Q5A0NQ1EVgjGyU5nIeEZn8U9utFXIvhPTxT1GOob0BRr/rs8O90tVj1EqfPckMIdShn5vHJ+t41JZW5zjv/9329j6XLTwoeNeYvfmYcYrS04wXnexF041G2uKYOXRr4S2T8DrdrqrMXLGRXS3jkZW2FYAQeLulFuwGwf4/U+15z2GmA4Go93uSgI5/gUP3qVdbH9oe+Z0Ull6CjCWPJMz57ypYhlYIKcdJqBo9/hlVfZg5qNNAFIrVO+EYgJtntrcwZVzroIpKQ+dgvHmmgHvDJPrd/YkkS84OAWKhbJ0U3FwHehjHnjtx1SUmcZuV5PVgGB2Nz0iogM5eYewuYV4DjekeCwx/mZaSmM0MM4unhyEamttM+xmVNDreZ+WVPGn9I/9yTCZg==
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: tekton-pipelines
    type: Opaque
