apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-gitops
spec:
  project: example-app
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:Roxxas96/example-app.git
    targetRevision: main
    path: infra/prod/kustomize
  ignoreDifferences:
    - group: "*"
      kind: CustomResourceDefinition
      name: customruns.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: extensions.dashboard.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: pipelineruns.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: pipelines.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: stepactions.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: taskruns.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: "*"
      kind: CustomResourceDefinition
      name: tasks.tekton.dev
      jsonPointers:
        - /spec/preserveUnknownFields
