apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - harbor-repo.sealedsecret.yaml
  - project.yaml
  - example-app-repo.sealedsecret.yaml
  - gitops.yaml
