name: CI

on:
  push:
    branches: [main]
    tags: ["*.*.*"]
  pull_request:

env:
  REGISTRY: harbor.roxxas96.net
  DOCKER_USERNAME: robot$example-app+github
  DOCKER_IMAGE_NAME: example-app/example-service
  HELM_USERNAME: robot$example-app-helm+github

jobs:
  chart-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - uses: hashicorp/setup-terraform@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Export kind config
        run: kind export kubeconfig --name chart-testing

      - name: Deploy test infrastructure
        run: |
          cd infra/test
          export TF_VAR_harbor_docker_username="${{ env.DOCKER_USERNAME }}"
          export TF_VAR_harbor_docker_password="${{ secrets.DOCKER_PASSWORD }}"
          terraform init
          terraform apply --auto-approve
          cd ../..

      - name: Run chart-testing (install)
        run: ct lint-and-install

  pre-commits:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: terraform-linters/setup-tflint@v4
      - uses: actions/setup-python@v3
      - name: Install helm-docs
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz
          tar xzf helm-docs_1.14.2_Linux_x86_64.tar.gz
          mv helm-docs /usr/local/bin/
      - name: Install hcledit
        run: |
          wget https://github.com/minamijoyo/hcledit/releases/download/v0.2.17/hcledit_0.2.17_linux_amd64.tar.gz
          tar xzf hcledit_0.2.17_linux_amd64.tar.gz
          mv hcledit /usr/local/bin/
      - name: Install tfupdate
        run: |
          wget https://github.com/minamijoyo/tfupdate/releases/download/v0.8.5/tfupdate_0.8.5_linux_amd64.tar.gz
          tar xzf tfupdate_0.8.5_linux_amd64.tar.gz
          mv tfupdate /usr/local/bin/
      - uses: arduino/setup-protoc@v3
      - uses: pre-commit/action@v3.0.1

  bump-version:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    concurrency:
      group: bump-version
      cancel-in-progress: false

    outputs:
      appVersion: ${{ steps.formatVersion.outputs.appVersion }}
      chartVersion: ${{ steps.formatVersion.outputs.chartVersion }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: 5.x

      - name: Install helm-docs
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz
          tar xzf helm-docs_1.14.2_Linux_x86_64.tar.gz
          mv helm-docs /usr/local/bin/

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Format version
        id: formatVersion
        run: |
          if [ "${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" = 0 ]; then
            echo "appVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}" >> $GITHUB_OUTPUT
          else
            echo "appVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}-rc${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" >> $GITHUB_OUTPUT
          fi
          OLD_CHART_VERSION=$(grep '^version:' example-service/chart/example-service/Chart.yaml | awk '{print $2}' | tr -d '"')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_CHART_VERSION"
          echo "chartVersion=$MAJOR.$MINOR.$((PATCH + 1))" >> $GITHUB_OUTPUT

      - name: Bump Version
        run: |
          sed -i 's/^version = ".*"/version = "${{ steps.formatVersion.outputs.appVersion }}"/' example-service/Cargo.toml
          sed -i '/name = "example-service"/{n;s/version = ".*"/version = "${{ steps.formatVersion.outputs.appVersion }}"/}' example-service/Cargo.lock
          sed -i 's/^appVersion: .*/appVersion: "${{ steps.formatVersion.outputs.appVersion }}"/' example-service/chart/example-service/Chart.yaml
          sed -i 's/^version: .*/version: "${{ steps.formatVersion.outputs.chartVersion }}"/' example-service/chart/example-service/Chart.yaml
          helm-docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: version-files
          path: |
            example-service/Cargo.toml
            example-service/Cargo.lock
            example-service/chart/example-service/Chart.yaml
            example-service/chart/example-service/README.md

  docker-build-push:
    runs-on: ubuntu-latest

    needs: [bump-version]

    permissions:
      contents: read
      packages: write
      id-token: write

    concurrency:
      group: docker-build-push
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Delete old version files
        run: |
          rm -f example-service/Cargo.toml
          rm -f example-service/Cargo.lock
          rm -f example-service/chart/example-service/Chart.yaml
          rm -f example-service/chart/example-service/README.md

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: version-files
          path: example-service

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Format tag template
        id: tags
        run: |
          IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "tags=$IMAGE_NAME:$BRANCH_NAME-$SHORT_SHA" >> $GITHUB_OUTPUT
          else
            echo "tags=$IMAGE_NAME:latest, $IMAGE_NAME:${{ needs.bump-version.outputs.appVersion }}" >> $GITHUB_OUTPUT
          fi
          ls -r

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: example-service
          file: example-service/Dockerfile
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Rust Cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-${{ runner.cache.artifact }}-${{ hashFiles('Cargo.lock') }}

      - name: Sign the published Docker image
        if: github.ref == 'refs/heads/main'
        run: echo "${{ steps.tags.outputs.tags }}" | tr ',' '\n' | xargs -I {} cosign sign -y {}@${{ steps.build-and-push.outputs.digest }}

  helm-publish:
    runs-on: ubuntu-latest

    needs: [bump-version]

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write
      id-token: write

    concurrency:
      group: helm-publish
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Delete old version files
        run: |
          rm -f example-service/Cargo.toml
          rm -f example-service/Cargo.lock
          rm -f example-service/chart/example-service/Chart.yaml
          rm -f example-service/chart/example-service/README.md

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: version-files
          path: example-service

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.HELM_USERNAME }}
          password: ${{ secrets.HELM_PASSWORD }}

      - name: Publish Helm chart to registry
        id: publish-helm
        run: |
          helm package example-service/chart/example-service/
          OUTPUT=$(helm push example-service-${{ needs.bump-version.outputs.chartVersion }}.tgz oci://${{ env.REGISTRY }}/example-app-helm 2>&1)

          echo $OUTPUT

          echo "tag=$(echo "$OUTPUT" | grep -oE "Pushed: [^ ]+" | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "digest=$(echo "$OUTPUT" | grep -oE "Digest: sha256:[a-f0-9]+" | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Sign the chart
        run: |
          cosign sign -y ${{ steps.publish-helm.outputs.tag }}@${{ steps.publish-helm.outputs.digest }}

  commit-version:
    runs-on: ubuntu-latest

    needs: [bump-version]

    if: github.ref == 'refs/heads/main'

    concurrency:
      group: commit-version
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - name: Delete old version files
        run: |
          rm -f example-service/Cargo.toml
          rm -f example-service/Cargo.lock
          rm -f example-service/chart/example-service/Chart.yaml
          rm -f example-service/chart/example-service/README.md

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: version-files
          path: example-service

      - name: Commit Version Bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: [skip ci] bump example-service version to ${{ needs.bump-version.outputs.appVersion }}"
          commit_options: -a
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
