externalURL: https://${host}

exposureType: ingress

ingress:
  core:
    ingressClassName: nginx
    hostname: ${host}
    annotations:
      cert-manager.io/cluster-issuer: external-prod
    tls: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
